/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/
  class Solution {
    public char findTheDifference(String s, String t) {
         int total = t.charAt(s.length());
        for (int i = 0; i < s.length(); i++)
            total += (t.charAt(i) - s.charAt(i));
        return (char) total;
    
    }
}
